### ISSUE TITLE
Should krowkee dependency and benchmark scripts be optional?

### ISSUE THREAD

**Issue by bwpriest** [LLNL/ygm-bench#1]
I've created a sketch embedding benchmark and am incorporating it into the benchmarking chassis. Should this become a normal part of the whole chassis, or should we create a conditional guard so that one can build and run `ygm-bench` without the krowkee stuff?

**Comment by steiltre** [comment]
Krowkee's only dependencies are YGM and Cereal, right?

I'm good with leaving out guards if this is the case.

**Comment by bwpriest** [comment]
Krowkee can optionally use `boost::container::flatmap` in its sparse sketch data structure, but the benchmark I put in there does not (presently). Based upon the root CMakeLists.txt, it looks like we are not building with Boost, so I did not include that feature. PR #2 incorporates krowkee into the workflow without guards.
